src/main/java/org/iot/hotelitybackend/common/config/CorsConfig.java, src/main/java/org/iot/hotelitybackend/common/constant/Constant.java, src/main/java/org/iot/hotelitybackend/common/vo/ResponseVO.java, src/main/java/org/iot/hotelitybackend/config/CorsConfig.java, src/main/java/org/iot/hotelitybackend/customer/controller/CustomerController.java, src/main/java/org/iot/hotelitybackend/customer/dto/CustomerDTO.java, src/main/java/org/iot/hotelitybackend/customer/service/CustomerService.java, src/main/java/org/iot/hotelitybackend/customer/service/CustomerServiceImpl.java
전체 고객 리스트 페이지 별 조회
전체 조회 시 페이징 처리
Resolves: #10 
어떤 변경 사항이 있나요?
=> Feat: "전체 고객 리스트 조회"

src/main/java/org/iot/hotelitybackend/hotelmanagement/aggregate/RoomEntity.java, src/main/java/org/iot/hotelitybackend/hotelmanagement/controller/BranchController.java, src/main/java/org/iot/hotelitybackend/hotelmanagement/controller/RoomController.java, src/main/java/org/iot/hotelitybackend/hotelmanagement/dto/RoomDTO.java, src/main/java/org/iot/hotelitybackend/hotelmanagement/service/BranchService.java, src/main/java/org/iot/hotelitybackend/hotelmanagement/service/BranchServiceImpl.java, src/main/java/org/iot/hotelitybackend/hotelmanagement/service/RoomService.java, src/main/java/org/iot/hotelitybackend/hotelmanagement/service/RoomServiceImpl.java, src/main/java/org/iot/hotelitybackend/hotelmanagement/vo/ResponseRoom.java
객실 전체 조회 기능 구현
Resolves: #20 
어떤 변경 사항이 있나요?
=> [Feat] 객실 전체 조회 기능 구현

src/main/java/org/iot/hotelitybackend/hotelmanagement/dto/RoomDTO.java, src/main/java/org/iot/hotelitybackend/hotelmanagement/repository/BranchRepository.java, src/main/java/org/iot/hotelitybackend/hotelmanagement/service/RoomServiceImpl.java
RoomDTO 에 다른 DTO 객체 전체를 붙이지 않고 다른 DTO에서 필요한 정보만 붙이도록 변경
Resolves: #20 
어떤 변경 사항이 있나요?
=> [Refactor] 객실 전체 조회 기능 수정

src/main/java/org/iot/hotelitybackend/employee/aggregate/DepartmentEntity.java, src/main/java/org/iot/hotelitybackend/employee/aggregate/EmployeeEntity.java, src/main/java/org/iot/hotelitybackend/employee/aggregate/PermissionEntity.java, src/main/java/org/iot/hotelitybackend/employee/aggregate/RankEntity.java, src/main/java/org/iot/hotelitybackend/employee/controller/EmployeeController.java, src/main/java/org/iot/hotelitybackend/employee/dto/DepartmentDTO.java, src/main/java/org/iot/hotelitybackend/employee/dto/EmployeeDTO.java, src/main/java/org/iot/hotelitybackend/employee/repository/EmployeeRepository.java, src/main/java/org/iot/hotelitybackend/employee/service/EmployeeService.java, src/main/java/org/iot/hotelitybackend/employee/service/EmployeeServiceImpl.java, src/main/java/org/iot/hotelitybackend/employee/vo/ResponseDepartment.java, src/main/java/org/iot/hotelitybackend/employee/vo/ResponseEmployee.java, src/main/java/org/iot/hotelitybackend/hotelmanagement/aggregate/AncillaryEntity.java, src/main/java/org/iot/hotelitybackend/hotelmanagement/aggregate/BranchEntity.java, src/main/java/org/iot/hotelitybackend/hotelservice/aggregate/ReservationEntity.java, src/main/java/org/iot/hotelitybackend/hotelservice/dto/ReservationDTO.java, src/main/java/org/iot/hotelitybackend/hotelservice/vo/ResponseReservation.java, src/main/java/org/iot/hotelitybackend/sales/aggregate/CouponEntity.java, src/main/java/org/iot/hotelitybackend/sales/aggregate/CouponIssueEntity.java, src/main/java/org/iot/hotelitybackend/sales/aggregate/MembershipEntity.java, src/main/java/org/iot/hotelitybackend/sales/aggregate/MembershipIssueEntity.java, src/main/java/org/iot/hotelitybackend/sales/aggregate/NoticeEntity.java, src/main/java/org/iot/hotelitybackend/sales/aggregate/VocEntity.java, src/main/java/org/iot/hotelitybackend/sales/dto/NoticeDTO.java, src/main/java/org/iot/hotelitybackend/sales/dto/VocDTO.java, src/main/java/org/iot/hotelitybackend/sales/service/NoticeServiceImpl.java, src/main/java/org/iot/hotelitybackend/sales/vo/ResponseVoc.java
조회 코드 JPA join 사용으로 수정
어떤 변경 사항이 있나요?
=> [Refactor] 직원 관련 조회 수정

src/main/java/org/iot/hotelitybackend/sales/controller/CouponController.java, src/main/java/org/iot/hotelitybackend/sales/controller/CouponIssueController.java, src/main/java/org/iot/hotelitybackend/sales/controller/NoticeController.java, src/main/java/org/iot/hotelitybackend/sales/service/CouponIssueService.java, src/main/java/org/iot/hotelitybackend/sales/service/CouponIssueServiceImpl.java, src/main/java/org/iot/hotelitybackend/sales/service/CouponService.java, src/main/java/org/iot/hotelitybackend/sales/service/CouponServiceImpl.java, src/main/java/org/iot/hotelitybackend/sales/service/NoticeService.java, src/main/java/org/iot/hotelitybackend/sales/service/NoticeServiceImpl.java, src/main/java/org/iot/hotelitybackend/sales/vo/RequestCoupon.java, src/main/java/org/iot/hotelitybackend/sales/vo/RequestCouponIssue.java, src/main/java/org/iot/hotelitybackend/sales/vo/RequestNotice.java
- 영업관리 부분에 쿠폰등록, 공지등록, 쿠폰발급 기능 추가(Post 요청)
- 쿠폰 발급 시 만료 기간 발급 시점부터 3개월 후로 설정
- 쿠폰 발급 시에 바코드 생성(국가코드 880, 사업자코드(임시) 3010 이후 랜덤)
#46 
#55 
#35 
어떤 변경 사항이 있나요?
=> [Feat] 영업관리/쿠폰등록, 공지등록, 쿠폰발급 기능 추가

src/main/java/org/iot/hotelitybackend/sales/aggregate/NoticeEntity.java, src/main/java/org/iot/hotelitybackend/sales/controller/CouponController.java, src/main/java/org/iot/hotelitybackend/sales/controller/NoticeController.java, src/main/java/org/iot/hotelitybackend/sales/service/CouponService.java, src/main/java/org/iot/hotelitybackend/sales/service/CouponServiceImpl.java, src/main/java/org/iot/hotelitybackend/sales/service/NoticeService.java, src/main/java/org/iot/hotelitybackend/sales/service/NoticeServiceImpl.java, src/main/java/org/iot/hotelitybackend/sales/vo/RequestModifyNotice.java
- 공지사항 삭제 기능
- 공지사항 수정 기능
- 쿠폰 수정 기능
- (쿠폰 삭제는 정책 상 DB에 기록이 남아있어야 될 것으로 판단해서 삭제 기능 추가 X)
#37 
#41 
#51 
어떤 변경 사항이 있나요?
=> [Feat] 공지사항 수정, 쿠폰 수정, 공지사항 삭제 기능 추가

src/main/java/org/iot/hotelitybackend/sales/aggregate/VocEntity.java, src/main/java/org/iot/hotelitybackend/sales/controller/VocController.java, src/main/java/org/iot/hotelitybackend/sales/dto/VocDTO.java, src/main/java/org/iot/hotelitybackend/sales/service/VocService.java, src/main/java/org/iot/hotelitybackend/sales/service/VocServiceImpl.java, src/main/java/org/iot/hotelitybackend/sales/vo/RequestReplyVoc.java
- VOC 답변 기능 추가
- 답변 등록 시 상태값 처리완료(1) 로 변경
- VOC Entity에서 voc_process_status 자료형 String에서 Integer로 변경
#83 
어떤 변경 사항이 있나요?
=> [Feat] VOC 답변 기능 추가

src/main/java/org/iot/hotelitybackend/sales/aggregate/NoticeEntity.java, src/main/java/org/iot/hotelitybackend/sales/dto/NoticeDTO.java
- 공지 다중 조건 검색 기능을 수정하였습니다.
- 공지에 branchCodeFk가 추가됨에 따른 기능 수정
#29 
어떤 변경 사항이 있나요?
=> [Refactor] 공지 다중 조건 검색 기능 수정

src/main/java/org/iot/hotelitybackend/marketing/controller/CampaignController.java, src/main/java/org/iot/hotelitybackend/marketing/controller/CampaignCustomerController.java, src/main/java/org/iot/hotelitybackend/marketing/controller/TemplateController.java, src/main/java/org/iot/hotelitybackend/marketing/dto/CampaignCustomerDTO.java, src/main/java/org/iot/hotelitybackend/marketing/repository/CampaignCustomerRepository.java, src/main/java/org/iot/hotelitybackend/marketing/repository/CampaignRepository.java, src/main/java/org/iot/hotelitybackend/marketing/repository/TemplateRepository.java, src/main/java/org/iot/hotelitybackend/marketing/service/CampaignCustomerService.java, src/main/java/org/iot/hotelitybackend/marketing/service/CampaignCustomerServiceImpl.java, src/main/java/org/iot/hotelitybackend/marketing/service/CampaignService.java, src/main/java/org/iot/hotelitybackend/marketing/service/CampaignServiceImpl.java, src/main/java/org/iot/hotelitybackend/marketing/service/TemplateService.java, src/main/java/org/iot/hotelitybackend/marketing/service/TemplateServiceImpl.java, src/main/java/org/iot/hotelitybackend/sales/repository/CouponRepository.java, src/main/java/org/iot/hotelitybackend/sales/repository/NoticeRepository.java, src/main/java/org/iot/hotelitybackend/sales/repository/VocRepository.java
- 마케팅 도메인 부분 조회 기능 추가(다중 조건 검색 기능 구현 예정)
#62 
#64 
#65 
#67 
어떤 변경 사항이 있나요?
=> [Feat]마케팅/템플릿,캠페인 조회 기능 추가

src/main/java/org/iot/hotelitybackend/employee/aggregate/EmploySpecification.java, src/main/java/org/iot/hotelitybackend/employee/aggregate/EmployeeEntity.java, src/main/java/org/iot/hotelitybackend/employee/controller/EmployeeController.java, src/main/java/org/iot/hotelitybackend/employee/dto/EmployeeDTO.java, src/main/java/org/iot/hotelitybackend/employee/repository/EmployeeRepository.java, src/main/java/org/iot/hotelitybackend/employee/service/EmployeeService.java, src/main/java/org/iot/hotelitybackend/employee/service/EmployeeServiceImpl.java, src/main/java/org/iot/hotelitybackend/hotelservice/aggregate/StayEntity.java
직원별 담당 투숙 내역 조회, 직원 다중 조건(지점별, 부서별, 이름) 조회 추가
Resolves: #36 #38 #39 #40 
어떤 변경 사항이 있나요?
=> [Feat] 직원 조회 기능

src/main/java/org/iot/hotelitybackend/sales/aggregate/CouponIssueSpecification.java, src/main/java/org/iot/hotelitybackend/sales/aggregate/VocSpecification.java, src/main/java/org/iot/hotelitybackend/sales/controller/CouponIssueController.java, src/main/java/org/iot/hotelitybackend/sales/controller/VocController.java, src/main/java/org/iot/hotelitybackend/sales/repository/CouponIssueRepository.java, src/main/java/org/iot/hotelitybackend/sales/service/CouponIssueService.java, src/main/java/org/iot/hotelitybackend/sales/service/CouponIssueServiceImpl.java, src/main/java/org/iot/hotelitybackend/sales/service/VocService.java, src/main/java/org/iot/hotelitybackend/sales/service/VocServiceImpl.java
- 다중 조건 조회할 때 고객 코드 별로 조회도 추가
어떤 변경 사항이 있나요?
=> [Refactor] 영업관리/쿠폰, VOC 조건추가(고객코드)

src/main/java/org/iot/hotelitybackend/marketing/aggregate/CampaignSpecification.java, src/main/java/org/iot/hotelitybackend/marketing/controller/CampaignController.java, src/main/java/org/iot/hotelitybackend/marketing/dto/CampaignDTO.java, src/main/java/org/iot/hotelitybackend/marketing/repository/CampaignRepository.java, src/main/java/org/iot/hotelitybackend/marketing/service/CampaignService.java, src/main/java/org/iot/hotelitybackend/marketing/service/CampaignServiceImpl.java, src/main/java/org/iot/hotelitybackend/sales/aggregate/CouponIssueSpecification.java
- 마케팅에서 캠페인 발송 내역 조회 시 특정 조건 검색 기능 추가
- 조건은 발송 일자, 직원 코드, 발송 방식
#103
#104
#105
어떤 변경 사항이 있나요?
=> [Refactor] 마케팅/캠페인 발송 내역에서 특정 조건 검색 기능 추가

build.gradle, src/main/java/org/iot/hotelitybackend/customer/aggregate/CustomerEntity.java, src/main/java/org/iot/hotelitybackend/customer/aggregate/CustomerSpecification.java, src/main/java/org/iot/hotelitybackend/customer/controller/CustomerController.java, src/main/java/org/iot/hotelitybackend/customer/controller/NationController.java, src/main/java/org/iot/hotelitybackend/customer/dto/CustomerDTO.java, src/main/java/org/iot/hotelitybackend/customer/dto/NationDTO.java, src/main/java/org/iot/hotelitybackend/customer/repository/CustomerRepository.java, src/main/java/org/iot/hotelitybackend/customer/service/CustomerService.java, src/main/java/org/iot/hotelitybackend/customer/service/CustomerServiceImpl.java, src/main/java/org/iot/hotelitybackend/customer/service/NationService.java, src/main/java/org/iot/hotelitybackend/customer/service/NationServiceImpl.java, src/main/java/org/iot/hotelitybackend/customer/vo/ResponseNation.java, src/main/java/org/iot/hotelitybackend/hotelmanagement/aggregate/AncillaryCategoryEntity.java, src/main/java/org/iot/hotelitybackend/hotelmanagement/aggregate/RoomSpecification.java, src/main/java/org/iot/hotelitybackend/hotelmanagement/controller/AncillaryController.java, src/main/java/org/iot/hotelitybackend/hotelmanagement/controller/RoomController.java, src/main/java/org/iot/hotelitybackend/hotelmanagement/dto/AncillaryCategoryDTO.java, src/main/java/org/iot/hotelitybackend/hotelmanagement/dto/AncillaryDTO.java, src/main/java/org/iot/hotelitybackend/hotelmanagement/dto/RoomDTO.java, src/main/java/org/iot/hotelitybackend/hotelmanagement/repository/RoomCategoryRepository.java, src/main/java/org/iot/hotelitybackend/hotelmanagement/service/AncillaryService.java, src/main/java/org/iot/hotelitybackend/hotelmanagement/service/AncillaryServiceImpl.java, src/main/java/org/iot/hotelitybackend/hotelmanagement/service/BranchServiceImpl.java, src/main/java/org/iot/hotelitybackend/hotelmanagement/service/RoomService.java, src/main/java/org/iot/hotelitybackend/hotelmanagement/service/RoomServiceImpl.java, src/main/java/org/iot/hotelitybackend/sales/aggregate/MembershipEntity.java, src/main/java/org/iot/hotelitybackend/sales/aggregate/MembershipIssueEntity.java, src/main/java/org/iot/hotelitybackend/sales/repository/MembershipIssueRepository.java, src/main/java/org/iot/hotelitybackend/sales/repository/MembershipRepository.java
객실 CRUD 완료, 부대시설 전체 조회 가능 구현 완료하였습니다.
Resolves: #60 
어떤 변경 사항이 있나요?
=> [Feat] 호텔관리 / 객실 CRUD 완료, 부대시설 전체 조회 가능 구현 완료

src/main/java/org/iot/hotelitybackend/hotelservice/aggregate/PaymentSpecification.java, src/main/java/org/iot/hotelitybackend/hotelservice/aggregate/ReservationSpecification.java, src/main/java/org/iot/hotelitybackend/hotelservice/aggregate/StaySpecification.java, src/main/java/org/iot/hotelitybackend/hotelservice/controller/PaymentController.java, src/main/java/org/iot/hotelitybackend/hotelservice/controller/StayController.java, src/main/java/org/iot/hotelitybackend/hotelservice/dto/ReservationDTO.java, src/main/java/org/iot/hotelitybackend/hotelservice/dto/StayDTO.java, src/main/java/org/iot/hotelitybackend/hotelservice/repository/ReservationRepository.java, src/main/java/org/iot/hotelitybackend/hotelservice/repository/StayRepository.java, src/main/java/org/iot/hotelitybackend/hotelservice/service/PaymentService.java, src/main/java/org/iot/hotelitybackend/hotelservice/service/PaymentServiceImpl.java, src/main/java/org/iot/hotelitybackend/hotelservice/service/ReservationService.java, src/main/java/org/iot/hotelitybackend/hotelservice/service/ReservationServiceImpl.java, src/main/java/org/iot/hotelitybackend/hotelservice/service/StayService.java, src/main/java/org/iot/hotelitybackend/hotelservice/service/StayServiceImpl.java
- 투숙 체크아웃 기능 구현 완료
- 결제 (다중 조건 필터링) 전체 내역 리스트 조회 완료
Resolves: #47 , #58 , #61 , #92 
어떤 변경 사항이 있나요?
=> [Feat] 호텔서비스/ 투숙 체크아웃 및 결제 조회 기능 구현 완료

src/main/java/org/iot/hotelitybackend/marketing/controller/TemplateController.java, src/main/java/org/iot/hotelitybackend/marketing/service/TemplateService.java, src/main/java/org/iot/hotelitybackend/marketing/service/TemplateServiceImpl.java, src/main/java/org/iot/hotelitybackend/marketing/vo/RequestTemplate.java
- 새로운 템플릿 등록, 기존 템플릿 수정, 기존 템플릿 삭제 기능 추가 완료
Resolves: #68 
Resolves: #73 
Resolves: #71 
어떤 변경 사항이 있나요?
=> [Feat] 마케팅/템플릿 등록, 수정, 삭제 기능 추가

src/main/java/org/iot/hotelitybackend/hotelmanagement/controller/AncillaryController.java, src/main/java/org/iot/hotelitybackend/hotelmanagement/service/AncillaryService.java, src/main/java/org/iot/hotelitybackend/hotelmanagement/service/AncillaryServiceImpl.java, src/main/java/org/iot/hotelitybackend/hotelmanagement/vo/RequestModifyFacility.java, src/main/java/org/iot/hotelitybackend/hotelmanagement/vo/RequestRegistFacility.java, src/main/java/org/iot/hotelitybackend/hotelmanagement/vo/ResponseAncillary.java
- 호텔관리에서 부대시설 등록, 수정, 삭제 기능 추가 완료
- 테이블(컬럼명) 수정 검토 필요
Resolves: #70 
Resolves: #66 
Resolves: #63 
어떤 변경 사항이 있나요?
=> [Feat] 호텔관리/부대시설 등록, 수정, 삭제 기능 추가

src/main/java/org/iot/hotelitybackend/hotelservice/aggregate/StayEntity.java, src/main/java/org/iot/hotelitybackend/hotelservice/controller/StayController.java, src/main/java/org/iot/hotelitybackend/hotelservice/service/StayService.java, src/main/java/org/iot/hotelitybackend/hotelservice/service/StayServiceImpl.java, src/main/java/org/iot/hotelitybackend/hotelservice/vo/RequestModifyStay.java
- 투숙 정보 수정, 삭제 기능 추가
- StayEntity 수정
Resolves: #52 
Resolves: #49 
어떤 변경 사항이 있나요?
=> [Feat] 호텔서비스/투숙 정보 수정, 삭제 기능 추가

src/main/java/org/iot/hotelitybackend/customer/controller/CustomerController.java, src/main/java/org/iot/hotelitybackend/customer/service/CustomerService.java, src/main/java/org/iot/hotelitybackend/customer/service/CustomerServiceImpl.java, src/main/java/org/iot/hotelitybackend/hotelservice/aggregate/StayEntity.java, src/main/java/org/iot/hotelitybackend/hotelservice/vo/RequestModifyStay.java
고객 정보 담긴 엑셀파일 다운로드 기능 구현 완료
Resolves: #112 
어떤 변경 사항이 있나요?
=> [Feat] 고객 엑셀 다운로드 기능

src/main/java/org/iot/hotelitybackend/customer/dto/CustomerDTO.java, src/main/java/org/iot/hotelitybackend/customer/repository/CustomerRepository.java, src/main/java/org/iot/hotelitybackend/customer/service/CustomerServiceImpl.java, src/main/java/org/iot/hotelitybackend/customer/vo/ResponseCustomer.java, src/main/java/org/iot/hotelitybackend/sales/repository/MembershipIssueRepository.java
- 특정 고객 정보 조회(고객의 멤버십 포함)
Resolves: #13 
어떤 변경 사항이 있나요?
=> [Feat]특정 고객 정보 조회(고객의 멤버십 포함)

src/main/java/org/iot/hotelitybackend/employee/aggregate/EmployeeEntity.java, src/main/java/org/iot/hotelitybackend/employee/controller/EmployeeController.java, src/main/java/org/iot/hotelitybackend/employee/dto/EmployeeDTO.java, src/main/java/org/iot/hotelitybackend/employee/service/EmployeeService.java, src/main/java/org/iot/hotelitybackend/employee/service/EmployeeServiceImpl.java, src/main/java/org/iot/hotelitybackend/employee/vo/RequestEmployee.java
직원 등록, 수정, 삭제 API 추가
Resolves: #99 #100 #101 
어떤 변경 사항이 있나요?
=> [Feat] 직원 등록/수정/삭제

src/main/java/org/iot/hotelitybackend/hotelmanagement/controller/AncillaryController.java, src/main/java/org/iot/hotelitybackend/hotelmanagement/controller/RoomController.java, src/main/java/org/iot/hotelitybackend/hotelmanagement/service/AncillaryService.java, src/main/java/org/iot/hotelitybackend/hotelmanagement/service/AncillaryServiceImpl.java, src/main/java/org/iot/hotelitybackend/hotelmanagement/service/RoomService.java, src/main/java/org/iot/hotelitybackend/hotelmanagement/service/RoomServiceImpl.java
- 객실, 부대시설 리스트 엑셀 파일 생성 및 다운로드 기능 구현 완료
- 다중 조건을 적용하여 검색된 리스트도 엑셀 파일 다운로드 가능
Resolves: #120 , #121 
어떤 변경 사항이 있나요?
=> [Feat] 객실, 부대시설 리스트 엑셀 파일 생성 및 다운로드 기능 구현 완료

src/main/java/org/iot/hotelitybackend/sales/controller/VocController.java, src/main/java/org/iot/hotelitybackend/sales/service/VocService.java, src/main/java/org/iot/hotelitybackend/sales/service/VocServiceImpl.java
VOC 엑셀 다운로드 구현 완료
Resolves: #125 
어떤 변경 사항이 있나요?
=> [Feat] VOC 엑셀 다운로드

src/main/java/org/iot/hotelitybackend/sales/controller/VocController.java, src/main/java/org/iot/hotelitybackend/sales/service/VocService.java, src/main/java/org/iot/hotelitybackend/sales/service/VocServiceImpl.java
VOC 삭제 기능 구현 완료
Resolves: #131
어떤 변경 사항이 있나요?
=> [Feat] VOC 삭제

src/main/java/org/iot/hotelitybackend/common/util/ExcelUtil.java, src/main/java/org/iot/hotelitybackend/hotelmanagement/aggregate/RoomSpecification.java, src/main/java/org/iot/hotelitybackend/hotelmanagement/controller/RoomController.java, src/main/java/org/iot/hotelitybackend/hotelmanagement/service/RoomService.java, src/main/java/org/iot/hotelitybackend/hotelmanagement/service/RoomServiceImpl.java
- 코드의 재사용성 향상을 위해 엑셀 다운로드 기능을 공통 코드로 분리
- common/util 경로에 ExcelUtil.java 클래스 추가
Resolves: #139 
어떤 변경 사항이 있나요?
=> [Refactor] 엑셀 다운로드 기능 공통 코드로 분리

src/main/java/org/iot/hotelitybackend/hotelservice/aggregate/PaymentSpecification.java, src/main/java/org/iot/hotelitybackend/hotelservice/aggregate/ReservationSpecification.java, src/main/java/org/iot/hotelitybackend/hotelservice/aggregate/StayEntity.java, src/main/java/org/iot/hotelitybackend/hotelservice/aggregate/StaySpecification.java, src/main/java/org/iot/hotelitybackend/hotelservice/controller/ReservationController.java, src/main/java/org/iot/hotelitybackend/hotelservice/controller/StayController.java, src/main/java/org/iot/hotelitybackend/hotelservice/dto/StayDTO.java, src/main/java/org/iot/hotelitybackend/hotelservice/service/ReservationService.java, src/main/java/org/iot/hotelitybackend/hotelservice/service/ReservationServiceImpl.java, src/main/java/org/iot/hotelitybackend/hotelservice/service/StayService.java, src/main/java/org/iot/hotelitybackend/hotelservice/service/StayServiceImpl.java
- 투숙 내역 전체 조회(다중 조건 검색) 시 모든 컬럼에 대한 조건 검색이 가능하도록 코드 리팩토링
Resolves: #129 
어떤 변경 사항이 있나요?
=> [Refactor] 호텔서비스/투숙 내역 전체 조회(다중 조건 검색) 코드 리팩토링

src/main/java/org/iot/hotelitybackend/hotelservice/controller/StayController.java, src/main/java/org/iot/hotelitybackend/hotelservice/dto/ReservationDTO.java, src/main/java/org/iot/hotelitybackend/hotelservice/dto/StayDTO.java, src/main/java/org/iot/hotelitybackend/hotelservice/service/ReservationServiceImpl.java, src/main/java/org/iot/hotelitybackend/hotelservice/service/StayService.java, src/main/java/org/iot/hotelitybackend/hotelservice/service/StayServiceImpl.java
- 투숙 정보 수정을 위한 투숙 코드로 특정 투숙 내역 조회 기능 구현
Resolves: #147 
어떤 변경 사항이 있나요?
=> [Feat] 호텔서비스/ 투숙 코드로 특정 투숙 내역 조회 기능 구현

src/main/java/org/iot/hotelitybackend/hotelservice/dto/StayDTO.java, src/main/java/org/iot/hotelitybackend/hotelservice/service/ReservationService.java, src/main/java/org/iot/hotelitybackend/hotelservice/service/ReservationServiceImpl.java, src/main/java/org/iot/hotelitybackend/hotelservice/service/StayServiceImpl.java, src/main/java/org/iot/hotelitybackend/sales/aggregate/NoticeEntity.java, src/main/java/org/iot/hotelitybackend/sales/aggregate/NoticeSpecification.java, src/main/java/org/iot/hotelitybackend/sales/aggregate/VocEntity.java, src/main/java/org/iot/hotelitybackend/sales/aggregate/VocSpecification.java, src/main/java/org/iot/hotelitybackend/sales/controller/NoticeController.java, src/main/java/org/iot/hotelitybackend/sales/controller/VocController.java, src/main/java/org/iot/hotelitybackend/sales/dto/NoticeDTO.java, src/main/java/org/iot/hotelitybackend/sales/dto/VocDTO.java, src/main/java/org/iot/hotelitybackend/sales/service/NoticeService.java, src/main/java/org/iot/hotelitybackend/sales/service/NoticeServiceImpl.java, src/main/java/org/iot/hotelitybackend/sales/service/VocService.java, src/main/java/org/iot/hotelitybackend/sales/service/VocServiceImpl.java
- VOC 및 공지 전체 조회 - 검색 조건 추가
- VOC 및 공지 전체 조회 - 정렬 추가
Resolves: #157 , #158 
어떤 변경 사항이 있나요?
=> [Refactor] 영업관리/VOC 및 공지 전체 조회 - 검색 조건 추가/정렬 추가

src/main/java/org/iot/hotelitybackend/customer/controller/CustomerController.java, src/main/java/org/iot/hotelitybackend/customer/dto/SelectCustomerDTO.java, src/main/java/org/iot/hotelitybackend/customer/service/CustomerService.java, src/main/java/org/iot/hotelitybackend/customer/service/CustomerServiceImpl.java, src/main/java/org/iot/hotelitybackend/sales/aggregate/CouponIssueSpecification.java, src/main/java/org/iot/hotelitybackend/sales/aggregate/CouponSpecification.java, src/main/java/org/iot/hotelitybackend/sales/controller/CouponController.java, src/main/java/org/iot/hotelitybackend/sales/controller/CouponIssueController.java, src/main/java/org/iot/hotelitybackend/sales/dto/CouponIssueDTO.java, src/main/java/org/iot/hotelitybackend/sales/service/CouponIssueService.java, src/main/java/org/iot/hotelitybackend/sales/service/CouponIssueServiceImpl.java, src/main/java/org/iot/hotelitybackend/sales/service/CouponService.java, src/main/java/org/iot/hotelitybackend/sales/service/CouponServiceImpl.java, src/main/java/org/iot/hotelitybackend/sales/service/VocServiceImpl.java
쿠폰 종류, 발급 쿠폰, 특정 고객 정보 조회 기능 수정 및 추가
Resolves: #138, #155, #156
어떤 변경 사항이 있나요?
=> [Refactor] 쿠폰, 특정고객 정보 조회 기능 수정

src/main/java/org/iot/hotelitybackend/customer/controller/CustomerController.java, src/main/java/org/iot/hotelitybackend/customer/service/CustomerService.java, src/main/java/org/iot/hotelitybackend/customer/service/CustomerServiceImpl.java
1명의 고객 등록 기능 구현 완료
어떤 변경 사항이 있나요?
=> [Feat] 고객/고객등록 한명 고객 등록 기능

src/main/java/org/iot/hotelitybackend/common/util/ExcelUtil.java, src/main/java/org/iot/hotelitybackend/hotelservice/controller/StayController.java, src/main/java/org/iot/hotelitybackend/hotelservice/service/StayService.java, src/main/java/org/iot/hotelitybackend/hotelservice/service/StayServiceImpl.java
부대시설, 예약, 투숙 리스트 엑셀 다운로드 기능 구현 완료
첫째줄에 컬럼명을 한국어 이름으로
(예시: reservationCodePk -> 예약코드)
Resolves: #116 , #117 , #171 
어떤 변경 사항이 있나요?
=> [Feat] 엑셀/부대시설, 예약, 투숙 리스트 엑셀 다운로드

src/main/java/org/iot/hotelitybackend/sales/controller/CouponController.java, src/main/java/org/iot/hotelitybackend/sales/service/CouponServiceImpl.java
쿠폰(종류) 엑셀 다운로드 기능 구현 완료
다운로드된 엑셀에서 멤버십등급명이 null 뜨는 문제 해결
Resolves: #174 
어떤 변경 사항이 있나요?
=> [Feat] 쿠폰 엑셀 다운로드

build.gradle, src/main/java/org/iot/hotelitybackend/common/config/AwsS3Config.java, src/main/java/org/iot/hotelitybackend/employee/aggregate/EmployeeEntity.java, src/main/java/org/iot/hotelitybackend/employee/controller/EmployeeController.java, src/main/java/org/iot/hotelitybackend/employee/service/AwsS3Service.java, src/main/java/org/iot/hotelitybackend/employee/service/AwsS3ServiceImpl.java
AWS S3 연동하여 이미지 업로드 후 이미지 URL DB에 저장
resolves #185 
어떤 변경 사항이 있나요?
=> [Feat] 직원 이미지 업로드

src/main/java/org/iot/hotelitybackend/customer/controller/CustomerController.java, src/main/java/org/iot/hotelitybackend/customer/controller/NationController.java, src/main/java/org/iot/hotelitybackend/customer/service/CustomerServiceImpl.java
예외처리를 이용해 프런트 출력 문장 작성 완료
어떤 변경 사항이 있나요?
- [x] 코드 리팩토링
=> [Refactor] 고객 정보 입력 예외처리

src/main/java/org/iot/hotelitybackend/hotelservice/dto/ReservationDTO.java, src/main/java/org/iot/hotelitybackend/hotelservice/dto/StayDTO.java, src/main/java/org/iot/hotelitybackend/hotelservice/service/ReservationServiceImpl.java, src/main/java/org/iot/hotelitybackend/hotelservice/service/StayServiceImpl.java
1. ReservationDTO와 StayDTO에 숙박 일자 필드 추가
2. ReservationService에서 체크인 일자와 체크아웃 일자를 통해 숙박일자를 계산하여 DTO에 매핑
3. StayService에서 ReservationService에 작성한 메소드를 사용하여 숙박 일자를 DTO에 매핑
Resolves: #194 
어떤 변경 사항이 있나요?
=> [Refactor] 호텔서비스/ReservationDTO와 StayDTO에 숙박일자 추가

src/main/java/org/iot/hotelitybackend/customer/aggregate/CustomerEntity.java, src/main/java/org/iot/hotelitybackend/hotelmanagement/aggregate/RoomCategoryEntity.java, src/main/java/org/iot/hotelitybackend/hotelmanagement/aggregate/RoomEntity.java, src/main/java/org/iot/hotelitybackend/hotelmanagement/aggregate/RoomSpecification.java, src/main/java/org/iot/hotelitybackend/hotelmanagement/controller/RoomController.java, src/main/java/org/iot/hotelitybackend/hotelmanagement/dto/RoomDTO.java, src/main/java/org/iot/hotelitybackend/hotelmanagement/service/RoomService.java, src/main/java/org/iot/hotelitybackend/hotelmanagement/service/RoomServiceImpl.java, src/main/java/org/iot/hotelitybackend/hotelservice/service/ReservationServiceImpl.java
객실 각종 미구현 정렬 부분 구현 완료
Resolves: #196 
어떤 변경 사항이 있나요?
=> [Feat] 객실 각종 미구현 정렬 부분 구현 완료

src/main/java/org/iot/hotelitybackend/hotelservice/controller/ReservationController.java, src/main/java/org/iot/hotelitybackend/hotelservice/service/ReservationService.java, src/main/java/org/iot/hotelitybackend/hotelservice/service/ReservationServiceImpl.java
연도별 예약 리스트 출력 기능 구현 완료
Resolves: #198 
어떤 변경 사항이 있나요?
=> [Feat] 연도별 예약 리스트 출력

src/main/java/org/iot/hotelitybackend/hotelmanagement/controller/RoomController.java, src/main/java/org/iot/hotelitybackend/hotelmanagement/service/RoomService.java, src/main/java/org/iot/hotelitybackend/hotelmanagement/service/RoomServiceImpl.java
객실 가격별 정렬 리팩토링
Refactor: #196 
어떤 변경 사항이 있나요?
=> [Refactor] 객실 가격별 정렬 리팩토링

src/main/java/org/iot/hotelitybackend/hotelmanagement/aggregate/RoomEntity.java, src/main/java/org/iot/hotelitybackend/hotelmanagement/controller/AncillaryController.java, src/main/java/org/iot/hotelitybackend/hotelmanagement/controller/RoomController.java, src/main/java/org/iot/hotelitybackend/hotelmanagement/dto/RoomDTO.java, src/main/java/org/iot/hotelitybackend/hotelmanagement/service/RoomService.java, src/main/java/org/iot/hotelitybackend/hotelmanagement/service/RoomServiceImpl.java
객실 방개수, 화장실개수, 상세설명 정렬 추가
Resolves: #196 
어떤 변경 사항이 있나요?
=> [Feat] 객실 각종 정렬 기능 추가

src/main/java/org/iot/hotelitybackend/hotelservice/controller/ReservationController.java, src/main/java/org/iot/hotelitybackend/hotelservice/repository/ReservationRepository.java, src/main/java/org/iot/hotelitybackend/hotelservice/service/ReservationService.java, src/main/java/org/iot/hotelitybackend/hotelservice/service/ReservationServiceImpl.java
- LocalDateTime 형식으로 인해 시간까지 정확히 일치하지 않으면 조회되지 않던 문제 해결
Resolves: #203 
어떤 변경 사항이 있나요?
=> [Refactor] 호텔서비스/예약-예약일자로 예약 내역 조회

src/main/java/org/iot/hotelitybackend/hotelservice/repository/StayRepository.java, src/main/java/org/iot/hotelitybackend/hotelservice/service/StayServiceImpl.java
투숙 체크인 시간을 기준으로 조회하도록 리팩토링
Refactor: #205
어떤 변경 사항이 있나요?
=> [Refactor] 투숙 일자별 리스트 조회 기능

src/main/java/org/iot/hotelitybackend/hotelservice/controller/ReservationController.java, src/main/java/org/iot/hotelitybackend/hotelservice/repository/ReservationRepository.java, src/main/java/org/iot/hotelitybackend/hotelservice/service/ReservationService.java, src/main/java/org/iot/hotelitybackend/hotelservice/service/ReservationServiceImpl.java, src/main/java/org/iot/hotelitybackend/hotelservice/vo/ReservationDashboardVO.java, src/main/java/org/iot/hotelitybackend/sales/controller/NoticeController.java, src/main/java/org/iot/hotelitybackend/sales/controller/VocController.java, src/main/java/org/iot/hotelitybackend/sales/repository/NoticeRepository.java, src/main/java/org/iot/hotelitybackend/sales/repository/VocRepository.java, src/main/java/org/iot/hotelitybackend/sales/service/NoticeService.java, src/main/java/org/iot/hotelitybackend/sales/service/NoticeServiceImpl.java, src/main/java/org/iot/hotelitybackend/sales/service/VocService.java, src/main/java/org/iot/hotelitybackend/sales/service/VocServiceImpl.java, src/main/java/org/iot/hotelitybackend/sales/vo/NoticeDashboardVO.java, src/main/java/org/iot/hotelitybackend/sales/vo/VocDashboardVO.java
- 예약 시간에 대하여 내림차순으로 최신 3개 조회
- 공지 코드에 대하여 내림차순으로 최신 3개 조회
- VOC 코드에 대하여 내림차순으로 최신 3개 조회
Resolves: #210
어떤 변경 사항이 있나요?
=> [Feat] 메인페이지용 공지, VOC, 예약 최신순 조회

src/main/java/org/iot/hotelitybackend/hotelmanagement/aggregate/RoomEntity.java, src/main/java/org/iot/hotelitybackend/hotelmanagement/controller/RoomController.java, src/main/java/org/iot/hotelitybackend/hotelmanagement/dto/RoomDTO.java, src/main/java/org/iot/hotelitybackend/hotelmanagement/service/RoomService.java, src/main/java/org/iot/hotelitybackend/hotelmanagement/service/RoomServiceImpl.java
=> Refactor: "roomLevelName"

src/main/java/org/iot/hotelitybackend/hotelmanagement/aggregate/RoomEntity.java
roomLevelName 안불러와지는 오류 수정
어떤 변경 사항이 있나요?
=> [Fix] roomLevelName 안불러와지는 오류 긴급 수정

src/main/java/org/iot/hotelitybackend/hotelmanagement/aggregate/RoomImageEntity.java, src/main/java/org/iot/hotelitybackend/hotelmanagement/controller/RoomImageController.java, src/main/java/org/iot/hotelitybackend/hotelmanagement/dto/RoomImageDTO.java, src/main/java/org/iot/hotelitybackend/hotelmanagement/dto/SelectRoomDTO.java, src/main/java/org/iot/hotelitybackend/hotelmanagement/repository/RoomImageRepository.java
room_image_tb 생성
어떤 변경 사항이 있나요?
=> [Feat] room_image_tb 생성

src/main/java/org/iot/hotelitybackend/hotelmanagement/repository/RoomImageRepository.java, src/main/java/org/iot/hotelitybackend/hotelmanagement/service/RoomServiceImpl.java
객실 조회 시 객실 이미지 리스트 조회
Resolves: #217
어떤 변경 사항이 있나요?
=> [Feat] 객실 조회 시 객실 이미지 리스트 조회

src/main/java/org/iot/hotelitybackend/marketing/controller/TemplateController.java, src/main/java/org/iot/hotelitybackend/marketing/service/TemplateService.java, src/main/java/org/iot/hotelitybackend/marketing/service/TemplateServiceImpl.java
템플릿 전체 조회(페이징 없음)
어떤 변경 사항이 있나요?
=> [Feat] 템플릿 전체 조회(페이징 없음)

src/main/java/org/iot/hotelitybackend/sales/repository/MembershipIssueRepository.java, src/main/java/org/iot/hotelitybackend/smpt/EmailController.java, src/main/java/org/iot/hotelitybackend/smpt/EmailService.java, src/main/java/org/iot/hotelitybackend/smpt/EmailServiceImpl.java, src/main/java/org/iot/hotelitybackend/smpt/RequestSendMailByLevelDTO.java
멤버십 등급별 메일 발송
메일 내용 첫 줄에 "{고객 이름}님, 안녕하세요. Hotelity 입니다." 들어가도록 설정
어떤 변경 사항이 있나요?
=> [Feat] 멤버십 등급별 메일 발송

src/main/resources/application.yml
Redis 경로 수정 후 jasypt 암호화 적용
어떤 변경 사항이 있나요?
=> [Refactor] Redis host 경로 수정

src/main/java/org/iot/hotelitybackend/sales/controller/MembershipController.java, src/main/java/org/iot/hotelitybackend/sales/service/MembershipService.java, src/main/java/org/iot/hotelitybackend/sales/service/MembershipServiceImpl.java
멤버십 전체 조회 시 페이징 추가
어떤 변경 사항이 있나요?
=> [Feat] 멤버십 전체 조회 시 페이징 추가

src/main/java/org/iot/hotelitybackend/hotelmanagement/aggregate/AncillaryEntity.java, src/main/java/org/iot/hotelitybackend/hotelmanagement/controller/AncillaryController.java, src/main/java/org/iot/hotelitybackend/hotelmanagement/service/AncillaryService.java, src/main/java/org/iot/hotelitybackend/hotelmanagement/service/AncillaryServiceImpl.java
부대시설 전체 조회 시 정렬 미구현 부분 구현(지점명, 부대시설카테고리명)
어떤 변경 사항이 있나요?
=> [Feat] 부대시설 전체 조회 시 정렬 미구현 부분 구현

src/main/java/org/iot/hotelitybackend/sales/aggregate/CouponEntity.java, src/main/java/org/iot/hotelitybackend/sales/service/CouponServiceImpl.java
쿠폰 전체조회 시 멤버십등급명으로 정렬 기능 구현
어떤 변경 사항이 있나요?
=> [Refactor] 쿠폰 전체조회 시 멤버십등급명으로 정렬 기능 구현

src/main/java/org/iot/hotelitybackend/chatgpt/controller/ChatGPTController.java, src/main/java/org/iot/hotelitybackend/chatgpt/service/ChatGPTService.java, src/main/java/org/iot/hotelitybackend/chatgpt/service/ChatGPTServiceImpl.java
1. 일별 예약
2. 월별 예약
3. 연도별 예약
4. 일별 결제
5. 월별 결제
6. 연도별 결제
총 6가지로 구분하여 GPT 프롬프팅하도록 변경
어떤 변경 사항이 있나요?
=> [Refactor] (일별 or 월별 or 연도별) * (예약 or 결제) 구분하여 GPT 프롬프팅

src/main/java/org/iot/hotelitybackend/chatgpt/controller/ChatGPTController.java, src/main/java/org/iot/hotelitybackend/chatgpt/service/ChatGPTService.java, src/main/java/org/iot/hotelitybackend/chatgpt/service/ChatGPTServiceImpl.java, src/main/java/org/iot/hotelitybackend/sales/repository/NoticeRepository.java, src/main/java/org/iot/hotelitybackend/sales/repository/VocRepository.java
현재 시각 기준 어제와 오늘의 공지/VOC 데이터 기반 GPT 프롬프팅
/chat/notices/daily
/chat/vocs/daily
어떤 변경 사항이 있나요?
=> [Feat] 현재 시각 기준 어제와 오늘의 공지/VOC 데이터 기반 GPT 프롬프팅

src/main/java/org/iot/hotelitybackend/hotelservice/service/PaymentServiceImpl.java
- 결제 조회 시 고객 명, 결제 타입 명 추가
어떤 변경 사항이 있나요?
=> [Refactor] 호텔서비스/결제-결제 조회 시 고객명, 결제타입명 추가

src/main/java/org/iot/hotelitybackend/chatgpt/service/ChatGPTServiceImpl.java, src/main/java/org/iot/hotelitybackend/customer/aggregate/CustomerEntity.java, src/main/java/org/iot/hotelitybackend/customer/service/CustomerServiceImpl.java, src/main/java/org/iot/hotelitybackend/hotelservice/dto/StayDTO.java, src/main/java/org/iot/hotelitybackend/hotelservice/repository/StayRepository.java, src/main/java/org/iot/hotelitybackend/hotelservice/service/StayServiceImpl.java
- 엑셀 업로드 시 멤버십 등급 일반으로 발급
어떤 변경 사항이 있나요?
=> [Refactor] 엑셀 업로드시 멤버십 등급 발급

src/main/java/org/iot/hotelitybackend/customer/service/CustomerServiceImpl.java, src/main/java/org/iot/hotelitybackend/hotelservice/aggregate/StaySpecification.java, src/main/java/org/iot/hotelitybackend/hotelservice/controller/StayController.java, src/main/java/org/iot/hotelitybackend/hotelservice/service/StayService.java, src/main/java/org/iot/hotelitybackend/hotelservice/service/StayServiceImpl.java
- 투숙 리스트 체크아웃 예정일로 정렬 기능 추가
어떤 변경 사항이 있나요?
=> [Refactor] 호텔서비스/투숙-체크아웃 예정일 정렬 조건 추가

src/main/java/org/iot/hotelitybackend/chatgpt/controller/ChatGPTController.java, src/main/java/org/iot/hotelitybackend/chatgpt/service/ChatGPTServiceImpl.java, src/main/java/org/iot/hotelitybackend/hotelservice/repository/ReservationRepository.java, src/main/java/org/iot/hotelitybackend/sales/aggregate/NoticeEntity.java, src/main/java/org/iot/hotelitybackend/sales/aggregate/VocEntity.java
- 더 정확한 결과 도출을 위한 GPT 프롬프팅 명령어 조정
- Several exception handling
(from 공지, VOC)
어떤 변경 사항이 있나요?
=> [Fix] 더 정확한 결과 도출을 위한 GPT 프롬프팅 명령어 조정

src/main/java/org/iot/hotelitybackend/chatgpt/service/ChatGPTServiceImpl.java, src/main/java/org/iot/hotelitybackend/common/vo/CustomerCriteria.java, src/main/java/org/iot/hotelitybackend/customer/controller/CustomerController.java, src/main/java/org/iot/hotelitybackend/customer/service/CustomerService.java, src/main/java/org/iot/hotelitybackend/customer/service/CustomerServiceImpl.java, src/main/java/org/iot/hotelitybackend/employee/controller/EmployeeController.java, src/main/java/org/iot/hotelitybackend/employee/service/EmployeeService.java, src/main/java/org/iot/hotelitybackend/employee/service/EmployeeServiceImpl.java, src/main/java/org/iot/hotelitybackend/employee/vo/EmployeeSearchCriteria.java, src/main/java/org/iot/hotelitybackend/hotelmanagement/controller/RoomController.java, src/main/java/org/iot/hotelitybackend/hotelmanagement/service/RoomService.java, src/main/java/org/iot/hotelitybackend/hotelmanagement/service/RoomServiceImpl.java, src/main/java/org/iot/hotelitybackend/hotelmanagement/vo/RoomSearchCriteria.java
고객, 직원, 객실 전체 조회 시 ModelAttribute 사용하도록 변경
Resolves: #237 , #238 , #239 
어떤 변경 사항이 있나요?
=> [Refactor] 고객, 직원, 객실 전체 조회 시 ModelAttribute 사용하도록 변경

src/main/java/org/iot/hotelitybackend/hotelmanagement/controller/AncillaryController.java, src/main/java/org/iot/hotelitybackend/hotelmanagement/service/AncillaryService.java, src/main/java/org/iot/hotelitybackend/hotelmanagement/service/AncillaryServiceImpl.java, src/main/java/org/iot/hotelitybackend/hotelmanagement/vo/AncillarySearchCriteria.java
부대시설 전체 조회 시 ModelAttribute 사용하도록 변경
Resolves: #241 
어떤 변경 사항이 있나요?
=> [Refactor] 부대시설 전체 조회 시 ModelAttribute 사용하도록 변경

src/main/java/org/iot/hotelitybackend/customer/service/CustomerServiceImpl.java, src/main/java/org/iot/hotelitybackend/hotelservice/controller/PaymentController.java, src/main/java/org/iot/hotelitybackend/hotelservice/service/PaymentService.java, src/main/java/org/iot/hotelitybackend/hotelservice/service/PaymentServiceImpl.java, src/main/java/org/iot/hotelitybackend/hotelservice/vo/PaymentSearchCriteria.java
부대시설 전체 조회 시 ModelAttribute 사용하도록 변경
Resolves: #243 
어떤 변경 사항이 있나요?
=> [Refactor] 결제 로그 전체 조회 시 ModelAttribute 사용하도록 변경

src/main/java/org/iot/hotelitybackend/marketing/controller/CampaignCustomerController.java, src/main/java/org/iot/hotelitybackend/marketing/service/CampaignCustomerService.java, src/main/java/org/iot/hotelitybackend/marketing/service/CampaignCustomerServiceImpl.java, src/main/java/org/iot/hotelitybackend/marketing/vo/CampaignCustomerSearchCriteria.java
캠페인발송 전체 조회 시 ModelAttribute 사용하도록 변경
Resolves: #249 
어떤 변경 사항이 있나요?
=> [Refactor] 캠페인발송 전체 조회 시 ModelAttribute 사용하도록 변경

src/main/java/org/iot/hotelitybackend/hotelservice/controller/ReservationController.java, src/main/java/org/iot/hotelitybackend/hotelservice/service/ReservationService.java, src/main/java/org/iot/hotelitybackend/hotelservice/service/ReservationServiceImpl.java, src/main/java/org/iot/hotelitybackend/sales/controller/CouponIssueController.java
Reservation 전체 조회 Pathvariable 이름과 criteria 변수명 같아서 생기는 조회 오류 수정
어떤 변경 사항이 있나요?
=> [Hotfix] Reservation 전체 조회 시 Pathvariable 변수명과 criteria 변수명 같아서 생기는 조회 버그 수정

src/main/java/org/iot/hotelitybackend/sales/aggregate/CouponIssueEntity.java, src/main/java/org/iot/hotelitybackend/sales/controller/CouponIssueController.java, src/main/java/org/iot/hotelitybackend/sales/service/CouponIssueServiceImpl.java
Coupon Issue 정렬 안되는 오류 수정
어떤 변경 사항이 있나요?
=> [Fix] Coupon Issue 정렬 안되는 오류 수정

src/main/java/org/iot/hotelitybackend/sales/aggregate/CouponIssueEntity.java, src/main/java/org/iot/hotelitybackend/sales/aggregate/NoticeEntity.java, src/main/java/org/iot/hotelitybackend/sales/controller/NoticeController.java, src/main/java/org/iot/hotelitybackend/sales/service/CouponIssueServiceImpl.java, src/main/java/org/iot/hotelitybackend/sales/service/NoticeService.java, src/main/java/org/iot/hotelitybackend/sales/service/NoticeServiceImpl.java, src/main/java/org/iot/hotelitybackend/sales/vo/NoticeSearchCriteria.java
공지 전체 조회 시 ModelAttribute 사용하도록 변경
Resolves: #256 
어떤 변경 사항이 있나요?
=> [Refactor] 공지 전체 조회 시 ModelAttribute 사용하도록 변경

src/main/java/org/iot/hotelitybackend/hotelmanagement/aggregate/AncillaryImageEntity.java, src/main/java/org/iot/hotelitybackend/hotelmanagement/controller/AncillaryController.java, src/main/java/org/iot/hotelitybackend/hotelmanagement/dto/AncillaryImageDTO.java, src/main/java/org/iot/hotelitybackend/hotelmanagement/dto/SelectAncillaryDTO.java, src/main/java/org/iot/hotelitybackend/hotelmanagement/repository/AncillaryImageRepository.java, src/main/java/org/iot/hotelitybackend/hotelmanagement/service/AncillaryService.java, src/main/java/org/iot/hotelitybackend/hotelmanagement/service/AncillaryServiceImpl.java
1. 특정 부대시설 조회 + 이미지 리스트 조회
2. 부대시설이미지 테이블 생성
Resolves: #258
어떤 변경 사항이 있나요?
=> [Feat] 특정 부대시설 조회 + 이미지 리스트 조회

src/main/java/org/iot/hotelitybackend/customer/service/CustomerServiceImpl.java, src/main/java/org/iot/hotelitybackend/sales/aggregate/VocEntity.java, src/main/java/org/iot/hotelitybackend/sales/controller/VocController.java, src/main/java/org/iot/hotelitybackend/sales/service/VocService.java, src/main/java/org/iot/hotelitybackend/sales/service/VocServiceImpl.java, src/main/java/org/iot/hotelitybackend/sales/vo/VocSearchCriteria.java
1. VOC 정렬, 필터 기능 구현
2. RequestParam -> ModelAttribute 로 변경
Resolves: #260 
어떤 변경 사항이 있나요?
=> [Feat] VOC 정렬, 필터 기능 구현 / RequestParam -> ModelAttribute 로 변경

src/main/java/org/iot/hotelitybackend/employee/aggregate/EmployeeEntity.java, src/main/java/org/iot/hotelitybackend/employee/service/EmployeeServiceImpl.java, src/main/java/org/iot/hotelitybackend/employee/vo/EmployeeSearchCriteria.java
Employee 정렬, 필터링 안되는 문제 해결
쿼리스트링에 
positionCodeFk
rankCodeFk
departmentCodeFk
branchCodeFk
이렇게 들어가야 함.
어떤 변경 사항이 있나요?
=> [Fix] Employee 정렬, 필터링 안되는 문제 해결

src/main/java/org/iot/hotelitybackend/hotelmanagement/service/AncillaryServiceImpl.java, src/main/java/org/iot/hotelitybackend/hotelmanagement/vo/RequestModifyFacility.java, src/main/java/org/iot/hotelitybackend/sales/controller/CouponController.java, src/main/java/org/iot/hotelitybackend/sales/service/CouponService.java, src/main/java/org/iot/hotelitybackend/sales/service/CouponServiceImpl.java
- 부대시설 카테고리 이름으로 수정할 수 있게 변경
- 불필요 주석 삭제
어떤 변경 사항이 있나요?
=> [Refactor] 부대시설 카테고리 이름으로 수정할 수 있게 변경 / 주석 삭제

src/main/java/org/iot/hotelitybackend/hotelservice/dto/ReservationDTO.java, src/main/java/org/iot/hotelitybackend/hotelservice/service/ReservationServiceImpl.java, src/main/java/org/iot/hotelitybackend/hotelservice/service/StayServiceImpl.java, src/main/java/org/iot/hotelitybackend/hotelservice/vo/RequestModifyStay.java, src/main/resources/application.yml
- 투숙 수정 시 받아오는 requestBody의 데이터 변경
- 체크인 일자로 조회 시 체크인 예정일이 나오지 않는 에러 해결(setDTOField 메소드 연결)
Resolves: #266 
어떤 변경 사항이 있나요?
=> [Refactor] 호텔서비스/ 투숙 수정 메소드 리팩토링

src/main/java/org/iot/hotelitybackend/customer/service/CustomerServiceImpl.java, src/main/java/org/iot/hotelitybackend/hotelservice/aggregate/StayEntity.java, src/main/java/org/iot/hotelitybackend/hotelservice/vo/StaySearchCriteria.java, src/main/java/org/iot/hotelitybackend/sales/service/VocServiceImpl.java, src/main/java/org/iot/hotelitybackend/sales/vo/RequestReplyVoc.java
- VOC 답변 로직 수정
- 투숙 체크아웃예정일, 숙박일수로 정렬 구현
어떤 변경 사항이 있나요?
=> [Refactor] 투숙 체크아웃예정일, 숙박일수로 정렬 구현

src/main/java/org/iot/hotelitybackend/sales/service/NoticeServiceImpl.java, src/main/java/org/iot/hotelitybackend/sales/vo/RequestNotice.java
- registNotice 수정, requestNotice에서 branchCodeFk 추가
어떤 변경 사항이 있나요?
=> [Refactor] RegistNotice 수정

src/main/java/org/iot/hotelitybackend/customer/controller/CustomerController.java, src/main/java/org/iot/hotelitybackend/customer/service/CustomerService.java, src/main/java/org/iot/hotelitybackend/customer/service/CustomerServiceImpl.java, src/main/java/org/iot/hotelitybackend/hotelmanagement/vo/RequestModifyCustomer.java, src/main/java/org/iot/hotelitybackend/sales/repository/MembershipIssueRepository.java
=> [Feat] 고객 정보 수정 기능

src/main/java/org/iot/hotelitybackend/hotelservice/repository/StayRepository.java, src/main/java/org/iot/hotelitybackend/hotelservice/service/StayServiceImpl.java
- 메인페이지 투숙 데이터 조회 오류 수정
- 체크아웃시간 기준으로 조회하는 것에서 체크인시간 기준으로 조회하도록 수정
어떤 변경 사항이 있나요?
=> [Fix] 메인페이지 투숙 데이터 조회 오류 수정

src/main/java/org/iot/hotelitybackend/filedownload/controller/FileDownloadController.java
tutorial.pdf 파일 업로드 리팩토링
어떤 변경 사항이 있나요?
=> [Refactor] tutorial.pdf 파일 업로드

src/main/java/org/iot/hotelitybackend/filedownload/controller/FileDownloadController.java
tutorial.pdf 파일 업로드 리팩토링
어떤 변경 사항이 있나요?
=> Refactor: "tutorial.pdf 파일 업로드"
